### ISSUE TITLE
doesnt work in lan single player mod

### ISSUE THREAD

**Issue by peachpotato** [Ewan-Selkirk/Dimension-Viewer#1]
I played with several friends through LAN single player but it said that no player was found when i hold tab i can only see the ping and when i type the command /refreshplayerlist it said that
[dimensionviewer] could not manually refresh. No players detected...

**Comment by Ewan-Selkirk** [comment]
I completely forgot about LAN servers. I'm not sure if I am able to support those, but I'll take a look when I get the chance. 

Thanks for the report!

**Comment by peachpotato** [comment]
will be waiting for the good news :D 
keep it up!
