### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by Dr-WeiAL** [Ewan-Selkirk/Dimension-Viewer#3]
listFormat has "%d - Dimension Name" but no Player Name, maybe you can add one?
This allows you to customize whether the player name is displayed in front of the world or behind it

Is it then possible to add a world alias? Sometimes I don't want to use its default name, or I want to change it to another language

**Comment by Ewan-Selkirk** [comment]
Adding an option for the player name should be easy. Having the dimension before the player name is not something that I had considered but I like the sound of it.

Aliasing is something that I thought about including at one point but forgot about. I have added it back to the list of things to work on, as it should be fairly easy to do.

Thanks for the suggestions!
